// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp67eO_iHDyupdgvwMj8xSUx6fTrPZcvQ',
    appId: '1:529218306025:web:fe94c5e1a4364357c7d578',
    messagingSenderId: '529218306025',
    projectId: 'social-media-live-streaming',
    authDomain: 'social-media-live-streaming.firebaseapp.com',
    storageBucket: 'social-media-live-streaming.appspot.com',
    measurementId: 'G-8P55XQBWHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEm0iqbl-5SeDRZPlj-Vy2JVX1qFrGWcw',
    appId: '1:529218306025:android:a1e7ef0d9f30cb6fc7d578',
    messagingSenderId: '529218306025',
    projectId: 'social-media-live-streaming',
    storageBucket: 'social-media-live-streaming.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0uJ9l0Jboa4nB2arp9fEz0vNY8Kmm8M',
    appId: '1:529218306025:ios:c9962083c8d16622c7d578',
    messagingSenderId: '529218306025',
    projectId: 'social-media-live-streaming',
    storageBucket: 'social-media-live-streaming.appspot.com',
    iosBundleId: 'com.example.skLiveViceGroupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0uJ9l0Jboa4nB2arp9fEz0vNY8Kmm8M',
    appId: '1:529218306025:ios:c9962083c8d16622c7d578',
    messagingSenderId: '529218306025',
    projectId: 'social-media-live-streaming',
    storageBucket: 'social-media-live-streaming.appspot.com',
    iosBundleId: 'com.example.skLiveViceGroupChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp67eO_iHDyupdgvwMj8xSUx6fTrPZcvQ',
    appId: '1:529218306025:web:8dc1b605acb66aa4c7d578',
    messagingSenderId: '529218306025',
    projectId: 'social-media-live-streaming',
    authDomain: 'social-media-live-streaming.firebaseapp.com',
    storageBucket: 'social-media-live-streaming.appspot.com',
    measurementId: 'G-67WBC1CV27',
  );

}